### ISSUE TITLE
the Introduction page is not working

### ISSUE THREAD

**Issue by Genius398** [Educational-Websites/JS-Tutorials#20]
https://user-images.githubusercontent.com/74092334/129470950-24f28eb1-810c-4001-a08e-7a94658a92bf.mp4

**Comment by Genius398** [comment]
now its working

**Comment by Genius398** [comment]
Sorry.. but lesson 3 is having the same bug.

**Comment by Genius398** [comment]
if anyone can solve this, please make a pull request

**Comment by Super45coder** [comment]
What' the issue?

**Comment by Super45coder** [comment]
Now lesson 2 is the only page that has the bug. check the bug discussion.

**Comment by httpanand** [comment]
> if anyone can solve this, please make a pull request

What's the problem?

**Comment by Genius398** [comment]
> What' the issue?

See the webpage
