### ISSUE TITLE
Before Contributing, read this

### ISSUE THREAD

**Issue by Genius398** [Educational-Websites/JS-Tutorials#27]
IF YOU ARE EVER PLANNING TO CONTRIBUTE, NEVER MERGE IN THE MAIN BRANCH. ALWAYS MAKE A PULL REQUEST

**Comment by Super45coder** [comment]
I fixed 9 bugs. Or, I think. Please review.

**Comment by Genius398** [comment]
> I fixed 9 bugs. Or, I think. Please review.

I know. I'm just reminding Sreehari to make pull requests

**Comment by somePythonProgrammer** [comment]
We should add contributing guidelines, and also, contributors should follow them.

**Comment by Genius398** [comment]
> We should add contributing guidelines, and also, contributors should follow them.

I already added them

**Comment by Super45coder** [comment]
Oh. Did you approve the pull requests?
________________________________

**Comment by Super45coder** [comment]
Sure.
________________________________

**Comment by Super45coder** [comment]
You did. Thanks!
