### ISSUE TITLE
Git Issue: The patch branches need to be merged to the main branch

### ISSUE THREAD

**Issue by hamiecod** [Educational-Websites/JS-Tutorials#82]
There are about 15 patch branches. The patch branches are merged to the main branch when the patch has been issued.

**Comment by Genius398** [comment]
they are used in pull requests. some of them are closed

**Comment by Super45coder** [comment]
Yes. But when merged, we can delete the patch.

**Comment by Genius398** [comment]
> Yes. But when merged, we can delete the patch.

Yes, but no one knows when we will need that patch

**Comment by hamiecod** [comment]
That's what Git is for, we can roll back to a commit whenever we want, and also if you want to still keep another copy of a patch easily accessible, we usually use tags for it and not branches.

**Comment by Genius398** [comment]
Ok... but I won't delete them

**Comment by Super45coder** [comment]
Okay.
________________________________
