### ISSUE TITLE
New Tutorial: Errors

### ISSUE THREAD

**Issue by e-coders** [Educational-Websites/JS-Tutorials#84]
New Tutorial: Errors

Everyone should get some Code Mistakes and they thinks its another mistake in javascript but in this way you can find any errors - If your Document have any Error so it will be Posted on Console by the Computer! So Press F12 Key to Open DeveloperTools then you will see a Console tab at the top, click it then you will see there have some texts in red? if there are no red texts so your document have no errors. You can also read the errors and it also gives link to the error line view your that line then check it that is your mistake and if there have no errors coming but not working so its because your all syntax is correct but there have some problems that are Hard to Fix.

**Comment by e-coders** [comment]
Add please!! 😙☺🙂

**Comment by somePythonProgrammer** [comment]
I'm on it!

**Comment by Super45coder** [comment]
I don't understand, so lets make a new tutorial! Or copyright footer!

**Comment by Genius398** [comment]
> I don't understand, so lets make a new tutorial! Or copyright footer!

He means to say we will make a new tutorial explaining how to use the console. and how to can be used for debugging

**Comment by Super45coder** [comment]
AHHHH. I see. Thanks! We can add controls at the website.
________________________________

**Comment by Genius398** [comment]
k

**Comment by Genius398** [comment]
I'm on it

**Comment by somePythonProgrammer** [comment]
I’m working on it on my fork…

**Comment by Genius398** [comment]
ok

**Comment by Super45coder** [comment]
I already know how to open console. You right click, press inspect, and go to the console section.

**Comment by Genius398** [comment]
yes

**Comment by Genius398** [comment]
also we  have 

`console.log("log");`
`console.warn("warn");`
`console.error("error");`

**Comment by Super45coder** [comment]
Yeah.
________________________________

**Comment by Genius398** [comment]
> I already know how to open console. You right click, press inspect, and go to the console section.

or CTRL + SHIFT + J

**Comment by Genius398** [comment]
I and @Super45coder  are working on HTML tutorials, so @e-coders , @Sreehari521 and @somePythonProgrammer should work on these errors tutorial

**Comment by Genius398** [comment]
im working on it

**Comment by somePythonProgrammer** [comment]
Ok

**Comment by Genius398** [comment]
YAAAYYYYYYY WOOOOHOOOOOOOOOOOOOO

**Comment by Super45coder** [comment]
YAY
________________________________
